// Generated by gencpp from file riki_msgs/Arm.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_ARM_H
#define RIKI_MSGS_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Arm_
{
  typedef Arm_<ContainerAllocator> Type;

  Arm_()
    : id(0)
    , time(0)
    , position(0)  {
    }
  Arm_(const ContainerAllocator& _alloc)
    : id(0)
    , time(0)
    , position(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _time_type;
  _time_type time;

   typedef int32_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::riki_msgs::Arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Arm_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_

typedef ::riki_msgs::Arm_<std::allocator<void> > Arm;

typedef boost::shared_ptr< ::riki_msgs::Arm > ArmPtr;
typedef boost::shared_ptr< ::riki_msgs::Arm const> ArmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riki_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'riki_msgs': ['/home/haopi3/rikirobot/catkin_ws/src/rikirobot_project/riki_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86d4dc4a5a3509adfd2df685044bbd29";
  }

  static const char* value(const ::riki_msgs::Arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86d4dc4a5a3509adULL;
  static const uint64_t static_value2 = 0xfd2df685044bbd29ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Arm";
  }

  static const char* value(const ::riki_msgs::Arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
int32 time\n\
int32 position\n\
";
  }

  static const char* value(const ::riki_msgs::Arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.time);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Arm_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_ARM_H
