// Generated by gencpp from file riki_msgs/Buzzer.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_BUZZER_H
#define RIKI_MSGS_MESSAGE_BUZZER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Buzzer_
{
  typedef Buzzer_<ContainerAllocator> Type;

  Buzzer_()
    : BUZZER1(0)  {
    }
  Buzzer_(const ContainerAllocator& _alloc)
    : BUZZER1(0)  {
  (void)_alloc;
    }



   typedef int32_t _BUZZER1_type;
  _BUZZER1_type BUZZER1;





  typedef boost::shared_ptr< ::riki_msgs::Buzzer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Buzzer_<ContainerAllocator> const> ConstPtr;

}; // struct Buzzer_

typedef ::riki_msgs::Buzzer_<std::allocator<void> > Buzzer;

typedef boost::shared_ptr< ::riki_msgs::Buzzer > BuzzerPtr;
typedef boost::shared_ptr< ::riki_msgs::Buzzer const> BuzzerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Buzzer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Buzzer_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riki_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'riki_msgs': ['/home/haopi3/rikirobot/catkin_ws/src/rikirobot_project/riki_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Buzzer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Buzzer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Buzzer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Buzzer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "961d0bf227fa8152deae5f5d68ec086e";
  }

  static const char* value(const ::riki_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x961d0bf227fa8152ULL;
  static const uint64_t static_value2 = 0xdeae5f5d68ec086eULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Buzzer";
  }

  static const char* value(const ::riki_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Buzzer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 BUZZER1\n\
";
  }

  static const char* value(const ::riki_msgs::Buzzer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Buzzer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.BUZZER1);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Buzzer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Buzzer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Buzzer_<ContainerAllocator>& v)
  {
    s << indent << "BUZZER1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.BUZZER1);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_BUZZER_H
