// Generated by gencpp from file riki_msgs/Led.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_LED_H
#define RIKI_MSGS_MESSAGE_LED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Led_
{
  typedef Led_<ContainerAllocator> Type;

  Led_()
    : LED1(0)
    , LED2(0)
    , LED3(0)  {
    }
  Led_(const ContainerAllocator& _alloc)
    : LED1(0)
    , LED2(0)
    , LED3(0)  {
  (void)_alloc;
    }



   typedef int32_t _LED1_type;
  _LED1_type LED1;

   typedef int32_t _LED2_type;
  _LED2_type LED2;

   typedef int32_t _LED3_type;
  _LED3_type LED3;





  typedef boost::shared_ptr< ::riki_msgs::Led_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Led_<ContainerAllocator> const> ConstPtr;

}; // struct Led_

typedef ::riki_msgs::Led_<std::allocator<void> > Led;

typedef boost::shared_ptr< ::riki_msgs::Led > LedPtr;
typedef boost::shared_ptr< ::riki_msgs::Led const> LedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Led_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Led_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riki_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'riki_msgs': ['/home/haopi3/rikirobot/catkin_ws/src/rikirobot_project/riki_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Led_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Led_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "872502f8a1825d221fb8b98672c92037";
  }

  static const char* value(const ::riki_msgs::Led_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x872502f8a1825d22ULL;
  static const uint64_t static_value2 = 0x1fb8b98672c92037ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Led";
  }

  static const char* value(const ::riki_msgs::Led_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 LED1\n\
int32 LED2\n\
int32 LED3\n\
";
  }

  static const char* value(const ::riki_msgs::Led_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Led_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.LED1);
      stream.next(m.LED2);
      stream.next(m.LED3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Led_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Led_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Led_<ContainerAllocator>& v)
  {
    s << indent << "LED1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LED1);
    s << indent << "LED2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LED2);
    s << indent << "LED3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.LED3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_LED_H
