// Generated by gencpp from file riki_msgs/RcMode.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_RCMODE_H
#define RIKI_MSGS_MESSAGE_RCMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct RcMode_
{
  typedef RcMode_<ContainerAllocator> Type;

  RcMode_()
    : mode(0)
    , vel(0.0)  {
    }
  RcMode_(const ContainerAllocator& _alloc)
    : mode(0)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _mode_type;
  _mode_type mode;

   typedef float _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::riki_msgs::RcMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::RcMode_<ContainerAllocator> const> ConstPtr;

}; // struct RcMode_

typedef ::riki_msgs::RcMode_<std::allocator<void> > RcMode;

typedef boost::shared_ptr< ::riki_msgs::RcMode > RcModePtr;
typedef boost::shared_ptr< ::riki_msgs::RcMode const> RcModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::RcMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::RcMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riki_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'riki_msgs': ['/home/haopi3/rikirobot/catkin_ws/src/rikirobot_project/riki_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RcMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::RcMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RcMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::RcMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RcMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::RcMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::RcMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0100e89a14982aa4b900add7d4fef3b1";
  }

  static const char* value(const ::riki_msgs::RcMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0100e89a14982aa4ULL;
  static const uint64_t static_value2 = 0xb900add7d4fef3b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::RcMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/RcMode";
  }

  static const char* value(const ::riki_msgs::RcMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::RcMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 mode\n\
float32 vel\n\
";
  }

  static const char* value(const ::riki_msgs::RcMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::RcMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RcMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::RcMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::RcMode_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    s << indent << "vel: ";
    Printer<float>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_RCMODE_H
