// Generated by gencpp from file riki_msgs/ServoAngle.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_SERVOANGLE_H
#define RIKI_MSGS_MESSAGE_SERVOANGLE_H

#include <ros/service_traits.h>


#include <riki_msgs/ServoAngleRequest.h>
#include <riki_msgs/ServoAngleResponse.h>


namespace riki_msgs
{

struct ServoAngle
{

typedef ServoAngleRequest Request;
typedef ServoAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ServoAngle
} // namespace riki_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::riki_msgs::ServoAngle > {
  static const char* value()
  {
    return "b1d39e7bb90536edb373b61068d04284";
  }

  static const char* value(const ::riki_msgs::ServoAngle&) { return value(); }
};

template<>
struct DataType< ::riki_msgs::ServoAngle > {
  static const char* value()
  {
    return "riki_msgs/ServoAngle";
  }

  static const char* value(const ::riki_msgs::ServoAngle&) { return value(); }
};


// service_traits::MD5Sum< ::riki_msgs::ServoAngleRequest> should match 
// service_traits::MD5Sum< ::riki_msgs::ServoAngle > 
template<>
struct MD5Sum< ::riki_msgs::ServoAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::riki_msgs::ServoAngle >::value();
  }
  static const char* value(const ::riki_msgs::ServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::riki_msgs::ServoAngleRequest> should match 
// service_traits::DataType< ::riki_msgs::ServoAngle > 
template<>
struct DataType< ::riki_msgs::ServoAngleRequest>
{
  static const char* value()
  {
    return DataType< ::riki_msgs::ServoAngle >::value();
  }
  static const char* value(const ::riki_msgs::ServoAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::riki_msgs::ServoAngleResponse> should match 
// service_traits::MD5Sum< ::riki_msgs::ServoAngle > 
template<>
struct MD5Sum< ::riki_msgs::ServoAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::riki_msgs::ServoAngle >::value();
  }
  static const char* value(const ::riki_msgs::ServoAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::riki_msgs::ServoAngleResponse> should match 
// service_traits::DataType< ::riki_msgs::ServoAngle > 
template<>
struct DataType< ::riki_msgs::ServoAngleResponse>
{
  static const char* value()
  {
    return DataType< ::riki_msgs::ServoAngle >::value();
  }
  static const char* value(const ::riki_msgs::ServoAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_SERVOANGLE_H
