// Generated by gencpp from file riki_msgs/Ultrasonic.msg
// DO NOT EDIT!


#ifndef RIKI_MSGS_MESSAGE_ULTRASONIC_H
#define RIKI_MSGS_MESSAGE_ULTRASONIC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace riki_msgs
{
template <class ContainerAllocator>
struct Ultrasonic_
{
  typedef Ultrasonic_<ContainerAllocator> Type;

  Ultrasonic_()
    : front(0.0)
    , left(0.0)
    , right(0.0)  {
    }
  Ultrasonic_(const ContainerAllocator& _alloc)
    : front(0.0)
    , left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _front_type;
  _front_type front;

   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::riki_msgs::Ultrasonic_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::riki_msgs::Ultrasonic_<ContainerAllocator> const> ConstPtr;

}; // struct Ultrasonic_

typedef ::riki_msgs::Ultrasonic_<std::allocator<void> > Ultrasonic;

typedef boost::shared_ptr< ::riki_msgs::Ultrasonic > UltrasonicPtr;
typedef boost::shared_ptr< ::riki_msgs::Ultrasonic const> UltrasonicConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::riki_msgs::Ultrasonic_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::riki_msgs::Ultrasonic_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace riki_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'riki_msgs': ['/home/haopi3/rikirobot/catkin_ws/src/rikirobot_project/riki_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::riki_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::riki_msgs::Ultrasonic_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::riki_msgs::Ultrasonic_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c69b6708342d9a4721f01e55dbb0d446";
  }

  static const char* value(const ::riki_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc69b6708342d9a47ULL;
  static const uint64_t static_value2 = 0x21f01e55dbb0d446ULL;
};

template<class ContainerAllocator>
struct DataType< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "riki_msgs/Ultrasonic";
  }

  static const char* value(const ::riki_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 front\n\
float32 left\n\
float32 right \n\
";
  }

  static const char* value(const ::riki_msgs::Ultrasonic_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ultrasonic_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::riki_msgs::Ultrasonic_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::riki_msgs::Ultrasonic_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<float>::stream(s, indent + "  ", v.front);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIKI_MSGS_MESSAGE_ULTRASONIC_H
